spring:
  application:
    name: RepSetGoApi

  # application.yml
  datasource:
    url: jdbc:postgresql://dpg-d056isa4d50c73agjjt0-a:5432/repsetgo
    username: repsetgo_user
    password: ${DB_PWD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9090

token:
  secret_key: D7jXQdlIhxL57wV2ihGSjgICnjN44Vhe
  expiration_milli_seconds: 3600000