spring:
  application:
    name: RepSetGoApi

  datasource:
    url: jdbc:mysql://localhost:3306/repsetgo
    username: root
    password: DEEPAK@b1304
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 9090

token:
  secret_key: D7jXQdlIhxL57wV2ihGSjgICnjN44Vhe
  expiration_milli_seconds: 3600000