spring:
  application:
    name: RepSetGoApi

  datasource:
    url: jdbc:mysql://sql205.infinityfree.com:3306/if0_38823153_repsetgo
    username: if0_38823153
    password: ${DB_PWD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 9090

token:
  secret_key: D7jXQdlIhxL57wV2ihGSjgICnjN44Vhe
  expiration_milli_seconds: 3600000